---
title: "package_dev"
---

```{r setup, include=FALSE}

library(devtools)
library(testthat)

```


To do:
correlation function (pval, pairwise.complete.obs)





```{r initial setup}

use_mit_license()
use_readme_rmd()
use_pipe()

```

```{r package startup}

load_all()

```



Dependencies
```{r}

use_package("ggplot2")
use_package("ggrepel")
use_package("rlang")
use_package("scales")
use_package("magrittr")
use_package("dplyr")

use_package("openxlsx")
use_package("ComplexHeatmap")
use_package("circlize")

use_package("ggdendro")
use_package("paletteer")
use_package("BiocParallel")
use_package("patchwork")
use_package("limma")
use_package("edgeR")
use_package("DESeq2")
use_package("GSVA")
use_package("fgsea")
use_package("tximport")
use_package("AnnotationDbi")
use_package("igraph")
use_package("msigdbr")

use_package("rtracklayer", type = "Suggests")
use_package("sparseMatrixStats", type = "Suggests")
use_package("tidygraph", type = "Suggests")
use_package("graphlayouts", type = "Suggests")

use_package("GSEABase", type = "Suggests")
use_package("IHW", type = "Suggests")
use_package("biomaRt", type = "Suggests")
use_package("clusterProfiler", type = "Suggests")

use_package("org.Hs.eg.db", type = "Suggests")
use_package("colorDF", type = "Suggests")
use_package("colourpicker", type = "Suggests")
use_package("prismatic", type = "Suggests")
use_package("dendsort", type = "Suggests")
use_package("crayon", type = "Suggests")
use_package("qualpalr", type = "Suggests")

use_package("survival", type = "Suggests")
use_package("survminer", type = "Suggests")
use_package("rms", type = "Suggests")

use_package("cowplot", type = "Suggests")
use_package("missMDA", type = "Suggests")
use_package("plyr", type = "Suggests")
use_package("tibble", type = "Suggests")
use_package("tidyr", type = "Suggests")
use_package("yaml", type = "Suggests")

```

    
Add R scripts
```{r}

use_r("meta_functions.R")
use_r("plotting_functions")
use_r("gene_functions.R")
use_r("imports.R")


```


Update documentation
```{r}

# Code > Insert Roxygen Skeleton
document()
# devtools::build_manual()
# roxygen2::roxygenize()
```



Add unit tests
```{r}

lapply(list.files("R/", pattern = ".R"), use_test)

```


Test/check
```{r check}

# test()
check() # or Build > Check Package

```


```{r}

usethis::use_build_ignore("package_dev.Rmd")
usethis::use_build_ignore("desktop.ini")

```

```{r}

devtools::build_readme()

```


Install the package
```{r}

install()

```




